name: flutter_chess
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.15
  flutter_bloc: ^8.1.6
  equatable: ^2.0.3
  audioplayers: ^6.1.1
  google_fonts: ^6.2.1
  uuid: ^4.2.0
  ffi: ^2.1.4
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  aegiscore_bindings:
    path: /Users/dev/development/programming/aegiscore/bindings/dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  bloc_test: ^9.1.7
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21 # android min sdk version 21

flutter:
  uses-material-design: true

  assets:
    - assets/chess_pieces_svg/
